name: avivamiento_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0' # Usamos una restricción estándar moderna

dependencies:
  flutter:
    sdk: flutter

  # Firebase Core
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_messaging: ^15.1.3

  # UI & Animations
  cupertino_icons: ^1.0.8
  lottie: ^3.1.0
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9

  # Services & State Management
  flutter_riverpod: ^2.4.9
  image_picker: ^1.1.2
  http: ^1.2.1
  url_launcher: ^6.3.2
  webview_flutter: ^4.13.0
  jitsi_meet_flutter_sdk: ^11.5.1
  google_sign_in: ^6.2.1
  flutter_dotenv: ^5.1.0
  intl: ^0.19.0 # <-- VERSIÓN ACTUALIZADA Y COMPATIBLE CON NULL SAFETY
  shared_preferences: ^2.1.1
  audio_service: ^0.18.18
  just_audio: ^0.9.44
  youtube_player_iframe: ^5.2.0
  cached_network_image: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  build_runner: ^2.4.8
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets: 
    - assets/animations/
    - assets/images/
    - .env